version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:8080"  # Landing page
      - "5001:5001"  # Postiz
      - "5002:5002"  # PocketBase
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    restart: unless-stopped

  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz-local
    restart: unless-stopped
    environment:
      # Local development configuration
      MAIN_URL: "http://localhost:5001"
      FRONTEND_URL: "http://localhost:5001"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:5001/api"
      DATABASE_URL: "postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
      NOT_SECURED: "true"
    env_file:
      - .env.local
    volumes:
      - postiz_config:/config/
      - postiz_uploads:/uploads/
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    networks:
      - web
      - internal

  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db
    volumes:
      - postiz_postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db
      interval: 10s
      timeout: 3s
      retries: 3

  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis-local
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz_redis_data:/data
    networks:
      - internal

  pocketbase:
    image: spectado/pocketbase:latest
    volumes:
      - pocketbase_data:/pb/pb_data
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-admin@localhost}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-testpassword123}
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge
  internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  postiz_config:
  postiz_uploads:
  postiz_postgres_data:
  postiz_redis_data:
  pocketbase_data: